import './globals.css'
import { Lobster, Roboto_Flex } from 'next/font/google'

const lobster = Lobster({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-lobster'
})

const robotoFlex = Roboto_Flex({
  weight: '100',
  subsets: ['latin'],
  variable: '--font-roboto-flex'
})

export const metadata = {
  title: 'To Do App',
  description: 'Generated by Andres Medina fullstack dev',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${lobster.variable} ${robotoFlex.variable}`}>{children}</body>
    </html>
  )
}
